import type { Metadata } from "next";
import "./globals.css";
import { UserContextProvider } from "./user-context";
import { Toaster } from "sonner";

// export const metadata: Metadata = {
//   title: "React 19 Demo",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>React 19 Demo</title>
      </head>
      <Toaster position="top-right" richColors />
      <body className="antialiased">
        <UserContextProvider>{children}</UserContextProvider>
      </body>
    </html>
  );
}
